### ISSUE TITLE
please update dependencies

### ISSUE THREAD

**Issue by braco** [hieuvp/xpath-html#23]
especially xpath!

thanks :)

**Comment by hieuvp** [comment]
Thank you for your notification.
Can you create a PR for this? @braco

**Comment by bmeverett** [comment]
It looks like Dependabot updated it 1f9da49, but it hasn't been released yet. Can we release an updated version of this library with the update package?

**Comment by hieuvp** [comment]
Thanks, @bmeverett,
Releasing `xpath-html` to version `1.0.3` with the updated dependencies.

cc: @braco
